spring.application.name=depo

# Adatbázis
spring.datasource.url=jdbc:mysql://localhost:3306/warehouse_db
spring.datasource.username=root
spring.datasource.password=Krumpli8
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=ez_egy_nagyon_titkos_kulcs_123456789
jwt.expiration=86400000